exclude: [README.md]
gems: [jekyll-paginate]
host: 0.0.0.0
url: "http://trowelandlime.github.io"

source: .
destination: ./_site

paginate: 5
paginate_path: "blog/page:num"

future:      true
lsi:         false
permalink:   /blog/:year/:month/:day/:title/
encoding: 	 UTF-8
highlighter: pygments