exclude: [README.md]
host: 0.0.0.0
baseurl: "/trowel-and-lime"
url: "https://marekkultys.com"

destination: ./_site

permalink: /blog/:year/:month/:day/:title/
timezone: Europe/London


# FREE TO CHANGE
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end


# CANNOT CHANGE
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge